### ISSUE TITLE
ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

### ISSUE THREAD

**Issue by Sam-Sepioll** [n00py/LAPSDumper#1]
Getting the following error: 

Traceback (most recent call last):
  File "LAPSDumper/laps.py", line 31, in <module>
    main()
  File "//LAPSDumper/laps.py", line 25, in main
    c = Connection(s, user=args.domain + "\\" + args.username, password=args.password, authentication=NTLM, auto_bind=True)
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 356, in __init__
    self._do_auto_bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 380, in _do_auto_bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 153, in open
    raise LDAPSocketOpenError('invalid server address')
ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

**Comment by Sam-Sepioll** [comment]
Nvm, my bad, was able to solve it.

**Comment by TheMuntu** [comment]
> Nvm, my bad, was able to solve it.

Can you share how you solved it pleased?
